#!/usr/bin/env python3
"""
Comprehensive translation script for SMS System index.html
Adds translation keys and replaces Arabic strings with t() calls.
"""

import re

with open('index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# ============================================================
# PHASE 1: Add new translation keys to TRANSLATIONS object
# ============================================================

new_translations_ar = {
    # Login page
    'app_title': 'SMS — نظام إدارة المخزون والصيانة',
    'remember_me': 'تذكرني',
    'btn_login': 'تسجيل الدخول',
    'dark_mode': 'الوضع الليلي',
    'cloud_sync_title': 'المزامنة السحابية',
    'chart_line': 'رسم بياني',
    'chart_bar': 'أعمدة',
    'zero_selected': '0 محدد',
    'delete_bulk': 'حذف المحدد',
    'add_first_product': 'إضافة أول صنف',
    'add_first_category': 'إضافة أول تصنيف',
    'create_first_invoice': 'إنشاء أول فاتورة',
    'add_first_client': 'إضافة أول عميل',
    'add_first_visit': 'إضافة أول زيارة',
    'add_first_supplier': 'إضافة أول مورد',
    'intake_first_device': 'إذن استلام أول جهاز',
    'add_first_engineer': 'إضافة أول مهندس/فني',
    'search_purchases': 'بحث في الفواتير...',
    'no_treasury_expenses': 'لا توجد مصروفات خزينة',
    'no_indirect_expenses': 'لا توجد مصروفات غير مباشرة',
    'no_expenses': 'لا توجد مصروفات',
    'no_devices_maint': 'لا توجد أجهزة في الصيانة',
    'list_view': 'عرض قائمة',
    'card_view': 'عرض البطاقات',
    
    # Telegram settings
    'telegram_instructions': 'يبعت أي رسالة للبوت على Telegram (مثلاً /start) → ثم دوس "جلب Chat IDs" هنا → هيظهر الـ Chat ID تلقائي',
    'chat_id_label': 'Chat ID *',
    'chat_id_placeholder': 'مثلاً: 123456789',
    'notif_low_stock': 'تنبيه مخزون منخفض',
    'notif_unpaid': 'فواتير غير مدفوعة',
    'notif_devices_ready': 'أجهزة جاهزة للتسليم',
    'notif_warranty_expiry': 'تنبيهات انتهاء الضمان',
    'notif_daily_summary': 'ملخص يومي',
    'btn_test_notif': 'اختبار',
    
    # Cloud sync
    'sync_not_connected': 'غير متصل',
    'sync_auto_desc': 'المزامنة تعمل تلقائياً — كل التعديلات تتزامن بين جميع الأجهزة',
    'backup_desc': 'تصدير/استيراد كل بيانات النظام كملف JSON على جهازك',
    'export_backup': 'تصدير نسخة احتياطية',
    'import_backup': 'استيراد نسخة احتياطية',
    
    # Team permissions
    'permissions_label': 'الصلاحيات:',
    'role_admin_desc': 'مدير: كل شيء — تحكم كامل',
    'role_manager_desc': 'مشرف: المخزون + الفواتير + الصيانة + التقارير + الأسعار',
    'role_staff_desc': 'موظف: إنشاء فواتير + إضافة/صرف مخزون + استلام أجهزة — بدون أسعار أو أرباح',
    
    # Product form
    'sku_auto_placeholder': 'اتركه فارغ للتوليد التلقائي',
    'barcode_auto_placeholder': 'اتركه فارغ للتوليد التلقائي',
    'root_category': 'تصنيف رئيسي',
    'new_category_placeholder': 'اسم التصنيف الجديد',
    
    # Export/Import
    'export_title': 'تصدير',
    'export_desc': 'تصدير كل الأصناف إلى ملف Excel',
    'export_excel': 'تصدير Excel',
    'import_title': 'استيراد',
    'import_desc': 'استيراد أصناف من ملف Excel (يجب أن يتبع نفس التنسيق)',
    
    # Engineer specialties
    'specialty_general': 'عام',
    'specialty_mobiles': 'موبايلات',
    'specialty_laptop': 'لابتوب',
    'specialty_computer': 'كمبيوتر',
    'specialty_printers': 'طابعات',
    'specialty_networks': 'شبكات',
    'specialty_cameras': 'كاميرات',
    'specialty_other': 'أخرى',
    
    # Device form inline
    'client_name_placeholder': 'اسم العميل',
    'phone_placeholder': 'الهاتف',
    'engineer_name_placeholder': 'اسم المهندس',
    'phone_optional_placeholder': 'الهاتف (اختياري)',
    'name_placeholder': 'الاسم',
    
    # Repair history
    'order_label': 'الأمر:',
    'device_label': 'الجهاز:',
    'client_label_view': 'العميل:',
    'intake_date_label': 'الدخول:',
    'add_record': 'إضافة سجل',
    'date_label': 'التاريخ',
    'action_intake': 'استلام',
    'action_diagnosis': 'فحص',
    'action_repair': 'إصلاح',
    'action_testing': 'اختبار',
    'action_delivery': 'تسليم',
    'action_other': 'أخرى',
    'write_notes_placeholder': 'اكتب الوصف أو الملاحظات...',
    'select_engineer': '-- اختر المهندس --',
    'other_engineer': 'مهندس آخر...',
    
    # Invoice form
    'invoice_name_placeholder': 'الاسم',
    'invoice_phone_placeholder': 'الهاتف',
    
    # Payment ledger
    'current_balance': 'الرصيد الحالي',
    'record_payment': 'تسجيل دفعة',
    'set_balance': 'تعيين رصيد',
    'new_payment_title': 'تسجيل دفعة جديدة',
    'movement_type': 'نوع الحركة',
    'payment_in': 'دفعة واردة (سداد من العميل)',
    'payment_out': 'دفعة صادرة (دفع للمورد)',
    'add_debt': 'إضافة دين جديد',
    
    # JS toast messages
    'toast_username_not_found': 'اسم المستخدم غير موجود',
    'toast_wrong_password': 'كلمة المرور غير صحيحة',
    'toast_account_disabled': 'الحساب معطل',
    'activity_login': 'تسجيل دخول',
    'activity_logout': 'تسجيل خروج',
    'sync_connected': 'متصل ✅',
    'sync_connected_supabase': 'متصل — Supabase',
    'confirm_replace_data': 'سيتم استبدال كل البيانات الحالية. متابعة؟',
    'currency_egp': 'ج.م',
    'scanner_aim_camera': 'وجّه الكاميرا نحو الباركود',
    'toast_scanned': 'تم المسح',
    'confirm_product_not_found_add': 'لم يتم العثور على منتج بباركود: {code}\nهل تريد إضافة منتج جديد؟',
    'toast_added_item': 'تمت إضافة',
    'alert_qty_low': 'الكمية',
    'alert_min_stock': 'الحد الأدنى',
    'alert_ready_delivery': 'جاهز للتسليم',
    'unspecified': 'غير محدد',
    'alert_unpaid_invoices': 'فاتورة غير مدفوعة — الإجمالي',
    'no_alerts_msg': 'لا توجد تنبيهات ✅',
    'no_login_records': 'لا توجد عمليات تسجيل دخول',
    'no_movements': 'لا توجد حركات',
    'warranty_expired_since': 'ضمان {device} — {client} انتهى منذ {days} يوم',
    'warranty_expires_in': 'ضمان {device} — {client} ينتهي خلال {days} يوم',
    'chart_sales_label': 'المبيعات',
    'chart_purchases_label': 'المشتريات',
    'no_devices_chart': 'لا توجد أجهزة',
    'maint_under_repair': 'تحت الصيانة',
    'maint_done': 'خلصت',
    'maint_delivered': 'اتسلمت',
    'maint_completed': 'مكتملة',
    'no_data': 'لا توجد بيانات',
    'unknown': 'غير معروف',
    'this_month': 'هذا الشهر',
    'no_invoices_recent': 'لا توجد فواتير',
    'connected_label': 'متصل ✅',
    'not_connected_label': 'غير متصل',
    
    # Print invoice
    'sale_invoice_title': 'فاتورة بيع',
    'purchase_invoice_title': 'فاتورة شراء',
    'invoice_number': 'رقم الفاتورة',
    'invoice_date': 'التاريخ',
    'client_or_supplier': 'العميل',
    'supplier_label': 'المورد',
    'items_label': 'الأصناف',
    'qty_label': 'الكمية',
    'price_label': 'السعر',
    'total_label': 'الإجمالي',
    'paid_label': 'المدفوع',
    'remaining_label': 'المتبقي',
    'fully_paid': 'مدفوعة بالكامل',
    'contact_label': 'للتواصل',
    'by_label': 'بواسطة',
    'notes_label': 'ملاحظات',
    'attached_photos': 'الصور المرفقة',
    'btn_print': 'طباعة',
    'receipt_label': 'إيصال',
    'share_whatsapp': 'شير واتساب',
    'invoice_barcode': 'باركود الفاتورة',
    'qr_verify': 'QR للتحقق',
    'created_by_sms': 'تم الإنشاء بواسطة نظام SMS',
    'click_full_size': 'انقر للعرض بالحجم الكامل',
    'thank_you': 'شكراً لتعاملكم معنا',
    
    # Product actions
    'btn_view': 'عرض',
    'btn_edit': 'تعديل',
    'btn_add_stock': 'إضافة مخزون',
    'btn_reduce_stock': 'صرف مخزون',
    'existing_label': 'موجود',
    'low_stock_badge': 'مخزون منخفض',
    'available_label': 'المتاح',
    
    # Product view
    'view_code': 'الكود',
    'view_name': 'الاسم',
    'view_condition': 'الحالة',
    'view_type': 'النوع',
    'view_category': 'التصنيف',
    'view_barcode': 'الباركود',
    'view_buy_price': 'سعر الشراء',
    'view_sell_price': 'سعر البيع',
    'view_profit_unit': 'الربح/وحدة',
    'view_quantity': 'الكمية',
    'view_min_stock': 'الحد الأدنى',
    'view_description': 'الوصف',
    'print_barcode': 'طباعة باركود',
    'movement_history': 'سجل الحركات',
    'movement_in': 'إضافة',
    'movement_out': 'صرف',
    
    # Stock modal
    'stock_in_title': 'إضافة للمخزون',
    'stock_out_title': 'صرف من المخزون',
    'available_qty_only': 'الكمية المتاحة {qty} فقط',
    'stock_action_in': 'إضافة',
    'stock_action_out': 'صرف',
    'toast_stock_done': 'تم {action} {qty} وحدة',
    
    # Categories
    'all_categories_filter': 'كل التصنيفات',
    'no_category_option': 'بدون تصنيف',
    'root_category_option': 'تصنيف رئيسي',
    'no_categories_msg': 'لا توجد تصنيفات بعد',
    'items_count': 'صنف',
    'subcategory_count': 'تصنيف فرعي',
    'activity_new_category': 'تصنيف جديد',
    'confirm_delete_category': 'حذف هذا التصنيف؟',
    'activity_delete_category': 'حذف تصنيف',
    'modal_add_product_title': 'إضافة صنف جديد',
    'modal_edit_product_title': 'تعديل الصنف',
    'activity_update_product': 'تعديل صنف',
    'activity_new_product': 'صنف جديد',
    'confirm_delete_product': 'حذف الصنف "{name}"؟',
    'activity_delete_product': 'حذف صنف',
    
    # Export
    'excel_sheet_name': 'المخزون',
    'confirm_import_products': 'سيتم إضافة الأصناف من الملف. متابعة؟',
    'activity_import_products': 'استيراد {count} صنف',
    'toast_imported_count': 'تم استيراد {count} صنف',
    
    # Category page
    'no_main_category': 'بدون تصنيف رئيسي',
    'no_results': 'لا توجد نتائج',
    'prompt_new_main_category': 'اسم التصنيف الرئيسي الجديد:',
    'prompt_add_subcategory': 'إضافة تصنيف فرعي لـ "{name}":',
    'prompt_edit_category': 'تعديل اسم التصنيف:',
    'confirm_delete_cat_children': 'التصنيف "{name}" له تصنيفات فرعية. حذف الكل؟',
    'cant_delete_has_products': 'لا يمكن حذف "{name}" لأنه يحتوي على أصناف',
    'confirm_delete_cat': 'حذف التصنيف "{name}"؟',
    'add_subcategory': 'فرعي',
    
    # Clients
    'modal_add_client_title': 'إضافة عميل جديد',
    'modal_edit_client_title': 'تعديل بيانات العميل',
    'toast_client_updated': 'تم تعديل بيانات العميل',
    'toast_client_added': 'تم إضافة العميل',
    'confirm_delete_client': 'حذف العميل "{name}"؟',
    'toast_client_deleted': 'تم حذف العميل',
    'view_email': 'الإيميل',
    'view_factory_name': 'اسم المصنع',
    'view_factory_location': 'مكان المصنع',
    'view_factory_activity': 'نشاط المصنع',
    'view_balance': 'الرصيد',
    'view_notes': 'ملاحظات',
    'invoices_count': 'الفواتير',
    
    # Suppliers
    'modal_add_supplier_title': 'إضافة مورد جديد',
    'modal_edit_supplier_title': 'تعديل بيانات المورد',
    'toast_supplier_updated': 'تم تعديل بيانات المورد',
    'toast_supplier_added': 'تم إضافة المورد',
    'confirm_delete_supplier': 'حذف المورد "{name}"؟',
    'toast_supplier_deleted': 'تم حذف المورد',
    
    # Invoices
    'items_count_label': 'صنف',
    'btn_print_view': 'عرض/طباعة',
    'btn_record_payment': 'تسجيل دفع',
    'badge_paid': 'مدفوعة',
    'badge_partial': 'جزئي',
    'badge_unpaid': 'غير مدفوعة',
    'new_sale_invoice_title': 'فاتورة بيع جديدة',
    'new_purchase_invoice_title': 'فاتورة شراء جديدة',
    'select_client': 'اختر العميل',
    'other_add_client': '+ أخرى (إضافة عميل جديد)',
    'select_supplier': 'اختر المورد',
    'other_add_supplier': '+ أخرى (إضافة مورد جديد)',
    'client_party_label': 'العميل',
    'supplier_party_label': 'المورد',
    'edit_sale_invoice': 'تعديل فاتورة بيع',
    'edit_purchase_invoice': 'تعديل فاتورة شراء',
    'other_short': '+ أخرى',
    'select_product': 'اختر صنف',
    'other_add_product': '+ أخرى (إضافة صنف جديد)',
    'qty_placeholder': 'الكمية',
    'price_placeholder': 'السعر',
    'add_new_product_inline': 'إضافة صنف جديد',
    'product_name_required': 'اسم الصنف *',
    'cost_placeholder': 'التكلفة',
    'code_optional': 'الكود (اختياري)',
    'save_and_add': 'حفظ وإضافة',
    'toast_enter_product': 'أدخل اسم الصنف',
    'toast_add_one_item': 'أضف صنف واحد على الأقل',
    'toast_select_all_products': 'اختر المنتج لكل الأصناف',
    'toast_sale_saved': 'تم حفظ فاتورة البيع',
    'toast_purchase_saved': 'تم حفظ فاتورة الشراء',
    'invoice_sale_note': 'فاتورة بيع',
    'invoice_purchase_note': 'فاتورة شراء',
    
    # Bulk operations
    'selected_count_label': 'محدد',
    'admin_only_delete_invoices': 'مسح الفواتير متاح للمدير فقط',
    'confirm_delete_invoices': 'حذف {count} فاتورة؟ سيتم إرجاع المخزون. لا يمكن التراجع!',
    'toast_deleted_invoices': 'تم حذف {count} فاتورة',
    'confirm_delete_clients': 'حذف {count} عميل؟',
    'toast_deleted_clients': 'تم حذف {count} عميل',
    'confirm_delete_suppliers': 'حذف {count} مورد؟',
    'toast_deleted_suppliers': 'تم حذف {count} مورد',
    'confirm_delete_services': 'حذف {count} خدمة؟',
    'toast_deleted_services': 'تم حذف {count} خدمة',
    'confirm_delete_devices': 'حذف {count} جهاز؟',
    'toast_deleted_devices': 'تم حذف {count} جهاز',
    'confirm_delete_expenses': 'حذف {count} مصروف؟',
    'toast_deleted_expenses': 'تم حذف {count} مصروف',
    'confirm_delete_engineers': 'حذف {count} مهندس؟',
    'toast_deleted_engineers': 'تم حذف {count} مهندس',
    'admin_only_delete_products': 'مسح الأصناف متاح للمدير فقط',
    'confirm_delete_products': 'حذف {count} صنف؟ لا يمكن التراجع!',
    'toast_deleted_products': 'تم حذف {count} صنف',
    'admin_only_invoices': 'مسح الفواتير متاح للمدير فقط',
    'confirm_delete_invoice': 'حذف الفاتورة {num}؟',
    'toast_invoice_deleted': 'تم حذف الفاتورة',
    
    # Payment
    'remaining_amount': 'المبلغ المتبقي',
    'enter_paid_amount': 'أدخل المبلغ المدفوع:',
    'toast_payment_recorded': 'تم تسجيل الدفع',
    
    # Device statuses (JS)
    'js_under_repair': '🔧 تحت الصيانة',
    'js_done_not_delivered': '✅ خلصت ومتسلمتش',
    'js_delivered_not_paid': '📦 اتسلمت ومدفعتش',
    'js_completed': '💰 خلصت واتدفعت',
    
    # Device card/table
    'warranty_badge': 'ضمان',
    'months_label': 'شهر',
    'overdue_label': 'متأخر!',
    'order_number_label': 'رقم الأمر',
    'problem_label': 'المشكلة',
    'enter_name': 'أدخل الاسم',
    'toast_client_supplier_added': 'تم إضافة {type} بنجاح',
    'manage_clients': 'إدارة العملاء',
    'manage_suppliers': 'إدارة الموردين',
    'confirm_delete_entity': 'حذف "{name}"؟',
    'toast_entity_deleted': 'تم حذف {name}',
    'other_add_engineer': '+ أخرى (إضافة مهندس جديد)',
    'toast_enter_engineer_name': 'أدخل اسم المهندس',
    'toast_engineer_added': 'تم إضافة المهندس بنجاح',
    'modal_new_device_title': 'إذن استلام جهاز جديد',
    'other_add_client_short': '+ أخرى (إضافة عميل جديد)',
    'modal_edit_device_title': 'تعديل أمر الصيانة',
    'toast_device_updated': 'تم تعديل أمر الصيانة',
    'toast_device_created': 'تم إنشاء إذن الاستلام',
    'maint_expense_note': 'صيانة - أمر',
    'deadline_not_set': 'غير محدد',
    'toast_device_assigned': 'تم تخصيص الجهاز "{device}" للمهندس {engineer}',
    'activity_assign_device': 'تخصيص جهاز "{device}" (أمر {order}) للمهندس {engineer}',
    'task_assigned_title': 'تم تخصيص المهمة',
    'task_assigned_desc': 'تم تخصيص الجهاز للمهندس',
    'engineer_assigned': 'المهندس:',
    'device_assigned': 'الجهاز:',
    'problem_assigned': 'المشكلة:',
    'deadline_assigned': 'الموعد النهائي:',
    'instructions_label': 'تعليمات:',
    'btn_done': 'تم',
    
    # Task completion
    'activity_task_complete': '{engineer} أتم مهمة الجهاز "{device}" (أمر {order}){status}',
    'on_time': ' — في الوقت',
    'late': ' — متأخر',
    'toast_task_complete_ontime': 'تم إتمام المهمة في الوقت — مكافأة {amount} للمهندس {engineer}',
    'toast_task_complete_late': 'تم إتمام المهمة (متأخر) — المهندس {engineer}',
    'toast_task_complete': 'تم إتمام المهمة بنجاح',
    'activity_warning': 'إنذار {count}/{limit} للمهندس {engineer} — جهاز "{device}" (أمر {order})',
    'toast_warning_sent': 'تم إرسال إنذار {count}/{limit} للمهندس {engineer}',
    'confirm_penalty': 'تطبيق عقوبة {amount} على المهندس {engineer}؟',
    'activity_penalty': 'عقوبة {amount} على المهندس {engineer} — تأخر في جهاز "{device}" (أمر {order})',
    'toast_penalty_applied': 'تم تطبيق العقوبة {amount} على المهندس {engineer}',
    'confirm_delete_maint_order': 'حذف أمر الصيانة {num}؟',
    'toast_maint_deleted': 'تم حذف أمر الصيانة',
    
    # Device parts
    'available_qty': 'متاح',
    'from_stock': 'من المخزون',
    'external_purchase': 'شراء خارجي',
    'select_part': 'اختر قطعة',
    'part_name_placeholder': 'اسم القطعة',
    'supplier_placeholder': 'المورد',
    'qty_placeholder_parts': 'الكمية',
    'price_placeholder_parts': 'السعر',
    'device_already_complete': 'الجهاز مكتمل بالفعل',
    'confirm_status_change': 'تغيير الحالة إلى: {status}؟',
    'toast_status_changed': 'تم تغيير الحالة إلى {status}',
    
    # Device view
    'view_order_num': 'رقم الأمر',
    'view_status': 'الحالة',
    'view_device': 'الجهاز',
    'view_specs': 'المواصفات',
    'view_problem': 'المشكلة',
    'view_intake_date': 'تاريخ الدخول',
    'view_client': 'العميل',
    'view_client_factory': 'مصنع العميل',
    'view_engineer': 'المهندس المسؤول',
    'view_warranty': 'الضمان',
    'no_warranty': 'لا يوجد ضمان',
    
    # Task details
    'task_status_pending': 'في الانتظار',
    'task_status_assigned': 'تم التخصيص',
    'task_status_completed': 'مكتمل',
    'task_status_overdue': 'متأخر',
    'task_details_title': 'تفاصيل المهمة',
    'task_status_label': 'حالة المهمة',
    'deadline_label': 'الموعد النهائي',
    'reward_label': 'المكافأة',
    'penalty_label': 'العقوبة',
    'warnings_label': 'الإنذارات',
    'task_instructions': 'تعليمات المهمة',
    'btn_complete_task': 'إتمام المهمة',
    'btn_warn': 'إنذار',
    'btn_penalize': 'عقوبة',
    'device_photos': 'صور الجهاز',
    'parts_used': 'القطع المستخدمة',
    'part_label': 'القطعة',
    'source_label': 'المصدر',
    'stock_source': 'مخزون',
    'external_source': 'خارجي',
    'stock_parts_cost': 'تكلفة قطع المخزون:',
    'external_parts_cost': 'تكلفة القطع الخارجية:',
    'extra_expenses': 'مصاريف إضافية:',
    'total_cost': 'التكلفة الإجمالية:',
    'selling_price': 'سعر البيع:',
    'profit_label': 'الربح:',
    'qr_maint_order': 'QR Code — أمر صيانة',
    'print_label': 'طباعة الملصق',
    'print_receipt': 'طباعة إيصال',
    'maint_order_details': 'تفاصيل أمر الصيانة',
    'maint_order_title': 'أمر صيانة',
    'maint_receipt_title': 'إيصال صيانة',
    'parts_cost_label': 'تكلفة القطع:',
    'thank_you_receipt': 'شكراً لتعاملكم معنا',
    
    # Accounting
    'no_clients_msg': 'لا يوجد عملاء',
    'no_suppliers_msg': 'لا يوجد موردين',
    'record_payment_btn': 'تسجيل دفعة',
    'revenue_details': 'تفاصيل الإيرادات',
    'expenses_details': 'تفاصيل المصروفات',
    'net_profit_details': 'تفاصيل صافي الربح',
    'revenue_sales': 'مبيعات',
    'revenue_maintenance': 'صيانة',
    'revenue_services': 'خدمات وزيارات',
    'expense_purchases': 'مشتريات',
    'expense_general': 'مصروفات عامة',
    'expense_maint_costs': 'تكاليف صيانة',
    'profit_sales_revenue': 'إيراد المبيعات',
    'profit_maint': 'ربح الصيانة',
    'profit_services': 'إيراد الخدمات',
    'profit_purchases_neg': 'المشتريات',
    'profit_expenses_neg': 'المصروفات',
    'total_sum': 'الإجمالي',
    
    # Payment ledger
    'payment_ledger_client': 'سجل مدفوعات عميل',
    'payment_ledger_supplier': 'سجل مدفوعات مورد',
    'select_option': 'اختر...',
    'no_movements_recorded': 'لا توجد حركات مسجلة',
    'payment_label': 'سداد',
    'debt_label': 'دين',
    'payment_out_label': 'دفع',
    'adjustment_label': 'تعديل',
    'invoice_ref': 'فاتورة',
    'set_balance_title': 'تعيين الرصيد يدوياً',
    'manual_adjustment': 'تعديل يدوي',
    'edit_movement': 'تعديل الحركة',
    'confirm_delete_movement': 'حذف هذه الحركة؟',
    'toast_movement_deleted': 'تم حذف الحركة',
    'toast_select_entity': 'اختر عميل أو مورد',
    'toast_enter_valid_amount': 'أدخل مبلغ صحيح',
    'toast_movement_saved': 'تم حفظ الحركة',
    
    # Expenses
    'expense_indirect': 'مصروفات غير مباشرة',
    'expense_treasury': 'مصروفات خزينة',
    'toast_expense_updated': 'تم تعديل المصروف',
    'toast_expense_added': 'تم إضافة المصروف',
    'confirm_delete_expense': 'حذف هذا المصروف؟',
    'toast_expense_deleted': 'تم حذف المصروف',
    
    # Services
    'modal_new_service_title': 'زيارة/خدمة جديدة',
    'modal_edit_service_title': 'تعديل الزيارة/الخدمة',
    'toast_service_updated': 'تم تعديل الخدمة',
    'toast_service_added': 'تم إضافة الخدمة',
    'confirm_delete_service': 'حذف هذه الخدمة؟',
    'toast_service_deleted': 'تم حذف الخدمة',
    'service_badge_pending': 'قيد الانتظار',
    'service_badge_in_progress': 'جاري التنفيذ',
    'service_badge_completed': 'مكتملة',
    'service_badge_cancelled': 'ملغاة',
    
    # Reports
    'daily_report_title': 'التقرير اليومي',
    'sale_invoices_title': 'فواتير البيع',
    'purchase_invoices_title': 'فواتير الشراء',
    'no_sales_msg': 'لا توجد مبيعات',
    'no_purchases_msg': 'لا توجد مشتريات',
    'expenses_title': 'المصروفات',
    'no_expenses_msg': 'لا توجد مصروفات',
    'maintenance_title': 'الصيانة',
    'devices_in': 'أجهزة دخلت',
    'devices_done': 'أجهزة خلصت',
    'monthly_report_title': 'التقرير الشهري',
    'daily_breakdown': 'تفصيل يومي',
    'th_day': 'اليوم',
    'th_sales_report': 'المبيعات',
    'th_purchases_report': 'المشتريات',
    'th_expenses_report': 'المصروفات',
    'th_profit_report': 'الربح',
    'maint_summary': 'ملخص الصيانة',
    'devices_completed': 'أجهزة مكتملة',
    'inventory_report_title': 'تقرير المخزون',
    'by_category': 'حسب التصنيف',
    'th_item_count': 'عدد الأصناف',
    'th_value': 'القيمة',
    'low_stock_items': 'أصناف منخفضة',
    'outstanding_report_title': 'المبالغ المستحقة',
    'total_outstanding': 'إجمالي المستحق',
    
    # Users
    'user_active': 'مفعل',
    'user_disabled': 'معطل',
    'modal_add_user_title': 'إضافة مستخدم جديد',
    'password_placeholder': 'كلمة المرور',
    'modal_edit_user_title': 'تعديل المستخدم',
    'password_keep_placeholder': 'اتركه فارغ لعدم التغيير',
    
    # Permissions
    'perm_dashboard': 'لوحة التحكم',
    'perm_inventory': 'المخزون — عرض',
    'perm_inventory_edit': 'المخزون — إضافة/تعديل/حذف',
    'perm_stock_movement': 'إضافة/صرف مخزون',
    'perm_view_prices': 'عرض الأسعار والأرباح',
    'perm_sales': 'البيع — عرض',
    'perm_sales_create': 'البيع — إنشاء فواتير',
    'perm_purchases': 'المشتريات — عرض',
    'perm_purchases_create': 'المشتريات — إنشاء فواتير',
    'perm_clients': 'العملاء',
    'perm_suppliers': 'الموردين',
    'perm_maintenance': 'ورشة الصيانة',
    'perm_maintenance_intake': 'استلام أجهزة',
    'perm_accounting': 'المحاسبة',
    'perm_reports': 'التقارير',
    'perm_settings': 'الإعدادات',
    'perm_users': 'إدارة المستخدمين',
    
    'toast_user_updated': 'تم تعديل المستخدم',
    'toast_enter_password': 'أدخل كلمة المرور',
    'toast_user_added': 'تم إضافة المستخدم',
    'toast_user_activated': 'تم تفعيل المستخدم',
    'toast_user_deactivated': 'تم تعطيل المستخدم',
    'confirm_delete_user': 'حذف هذا المستخدم؟',
    'toast_user_deleted': 'تم حذف المستخدم',
    
    # Engineers
    'modal_add_engineer_title': 'إضافة مهندس/فني جديد',
    'modal_edit_engineer_title': 'تعديل المهندس/الفني',
    'toast_engineer_updated': 'تم تحديث المهندس/الفني',
    'toast_engineer_saved': 'تم إضافة المهندس/الفني',
    'confirm_delete_engineer': 'حذف هذا المهندس/الفني؟',
    'confirm_engineer_has_devices': 'هذا المهندس/الفني مسؤول عن {count} جهاز. هل تريد المتابعة؟',
    'toast_engineer_deleted': 'تم حذف المهندس/الفني',
    
    # Repair history timeline
    'timeline_device_intake': 'استلام الجهاز',
    'timeline_device_name': 'الجهاز:',
    'timeline_problem': 'المشكلة:',
    'timeline_notes': 'ملاحظات:',
    'timeline_diagnosis': 'فحص وتشخيص',
    'timeline_repair': 'إصلاح',
    'timeline_testing': 'اختبار',
    'timeline_completion': 'اكتمال',
    'timeline_delivery': 'تسليم',
    'timeline_update': 'تحديث',
    'timeline_maint_complete': 'انتهاء الصيانة',
    'timeline_device_delivered': 'تسليم الجهاز للعميل',
    'timeline_process_complete': 'اكتمال العملية',
    'timeline_new_status': 'الحالة الجديدة:',
    'toast_fill_date_action': 'يرجى ملء التاريخ ونوع الإجراء',
    'toast_record_added': 'تم إضافة السجل',
    'toast_record_updated': 'تم تحديث السجل',
    'confirm_delete_record': 'هل أنت متأكد من حذف هذا السجل؟',
    'toast_record_deleted': 'تم حذف السجل',
    
    # Activity log
    'no_activity_log': 'لا يوجد سجل نشاط',
    
    # Telegram notifications
    'notif_low_stock_title': 'تنبيه مخزون منخفض',
    'notif_unpaid_title': 'فواتير غير مدفوعة',
    'notif_devices_ready_title': 'أجهزة جاهزة للتسليم',
    'notif_warranty_title': 'تنبيهات الضمان:',
    'notif_daily_summary_title': 'ملخص اليوم',
    
    'toast_enter_token': 'أدخل التوكن أولاً',
    'toast_token_failed': 'فشل — تأكد من التوكن',
    'unknown_name': 'مجهول',
    'no_new_messages': 'لا توجد رسائل جديدة. اطلب من المستلم يبعت /start للبوت وجرب تاني',
    'people_sent_bot': 'الأشخاص اللي بعتوا للبوت:',
    'btn_use': 'استخدام',
    'toast_found_chats': 'تم العثور على {count} محادثة',
    'toast_connection_err': 'خطأ في الاتصال',
    'toast_chat_id_copied': 'تم نسخ Chat ID',
    'toast_enter_token_chatid': 'أدخل التوكن و Chat ID',
    'toast_test_success': '✅ تجربة إشعار من نظام SMS — الاتصال يعمل بنجاح!',
    'toast_sent_success': 'تم الإرسال ✅',
    'toast_check_chatid': 'فشل — تحقق من Chat ID',
    'toast_check_token_chatid': 'تحقق من التوكن و Chat ID',
    'toast_test_all_sent': 'تم إرسال اختبار لكل المستلمين ✅',
    'toast_recipient_saved': 'تم حفظ المستلم ✅',
    'toast_enabled': 'تم التفعيل',
    'toast_disabled': 'تم التعطيل',
    'confirm_delete_recipient': 'حذف هذا المستلم؟',
    'toast_deleted_msg': 'تم الحذف',
    'toast_token_saved': 'تم حفظ التوكن ✅',
    'modal_add_recipient_title': 'إضافة مستلم',
    'modal_edit_recipient_title': 'تعديل مستلم',
    'notif_badge_stock': 'مخزون',
    'notif_badge_invoices': 'فواتير',
    'notif_badge_delivery': 'تسليم',
    'notif_badge_warranty': 'ضمان',
    'notif_badge_summary': 'ملخص',
    
    # Settings
    'test_client': 'عميل تجريبي',
    'test_supplier': 'مورد تجريبي',
    'test_invoice_note': 'فاتورة اختبارية',
    'test_purchase_note': 'فاتورة شراء اختبارية',
    'toast_test_data_added': 'تم إضافة {count} فاتورة اختبارية ✅',
    'return_from_invoice': 'مرتجع من فاتورة',
    'toast_return_created': 'تم إنشاء المرتجع',
    'no_barcode': 'لا يوجد باركود',
    
    # Custom lists
    'edit_list_btn': 'تعديل القائمة',
    'type_here': 'اكتب هنا...',
    'save_label': 'احفظ',
    'search_placeholder': 'بحث...',
    'choose': 'اختر',
    'other_option': 'أخرى...',
    'edit_list_title': 'تعديل القائمة',
    'add_new_item': 'إضافة عنصر جديد...',
    'btn_add': 'إضافة',
    'save_changes': '💾 حفظ التغييرات',
    'list_empty': 'القائمة فارغة',
    'confirm_delete_item': 'حذف "{item}"؟',
    'choose_default': 'اختر...',
    'other_add': '➕ أخرى...',
    
    # Expense categories defaults
    'expense_cat_rent': 'إيجار',
    'expense_cat_salaries': 'مرتبات',
    'expense_cat_utilities': 'كهرباء ومياه',
    'expense_cat_transport': 'نقل ومواصلات',
    'expense_cat_maintenance': 'صيانة',
    
    # Product types
    'type_accessory': 'اكسسوار',
    'type_cable': 'كابل',
    'type_charger': 'شاحن',
    
    # Payment statuses
    'pay_paid': 'مدفوع',
    'pay_unpaid': 'غير مدفوع',
    'pay_partial': 'جزئي',
    
    # Device status list
    'ds_under_repair': 'تحت الصيانة',
    'ds_repaired': 'تم الإصلاح',
    'ds_delivered': 'تم التسليم',
    'ds_completed': 'مكتملة',
    
    # Service status list
    'ss_scheduled': 'مجدول',
    'ss_ongoing': 'جاري',
    'ss_done': 'مكتمل',
    'ss_cancelled': 'ملغي',
    
    # Admin name
    'admin_name': 'المدير',
    
    # Misc JS
    'no_barcode_msg': 'لا يوجد باركود',
    'return_note': 'مرتجع من فاتورة {num}',
}

new_translations_en = {
    'app_title': 'SMS — Inventory & Maintenance System',
    'remember_me': 'Remember Me',
    'btn_login': 'Login',
    'dark_mode': 'Dark Mode',
    'cloud_sync_title': 'Cloud Sync',
    'chart_line': 'Line Chart',
    'chart_bar': 'Bar Chart',
    'zero_selected': '0 selected',
    'delete_bulk': 'Delete Selected',
    'add_first_product': 'Add First Product',
    'add_first_category': 'Add First Category',
    'create_first_invoice': 'Create First Invoice',
    'add_first_client': 'Add First Client',
    'add_first_visit': 'Add First Visit',
    'add_first_supplier': 'Add First Supplier',
    'intake_first_device': 'First Device Intake',
    'add_first_engineer': 'Add First Engineer/Tech',
    'search_purchases': 'Search invoices...',
    'no_treasury_expenses': 'No treasury expenses',
    'no_indirect_expenses': 'No indirect expenses',
    'no_expenses': 'No expenses',
    'no_devices_maint': 'No devices in maintenance',
    'list_view': 'List View',
    'card_view': 'Card View',
    'telegram_instructions': 'Send any message to the bot on Telegram (e.g. /start) → then click "Fetch Chat IDs" here → the Chat ID will appear automatically',
    'chat_id_label': 'Chat ID *',
    'chat_id_placeholder': 'e.g.: 123456789',
    'notif_low_stock': 'Low Stock Alert',
    'notif_unpaid': 'Unpaid Invoices',
    'notif_devices_ready': 'Devices Ready for Delivery',
    'notif_warranty_expiry': 'Warranty Expiry Alerts',
    'notif_daily_summary': 'Daily Summary',
    'btn_test_notif': 'Test',
    'sync_not_connected': 'Not Connected',
    'sync_auto_desc': 'Sync works automatically — all changes sync across all devices',
    'backup_desc': 'Export/import all system data as a JSON file on your device',
    'export_backup': 'Export Backup',
    'import_backup': 'Import Backup',
    'permissions_label': 'Permissions:',
    'role_admin_desc': 'Admin: Everything — full control',
    'role_manager_desc': 'Manager: Inventory + Invoices + Maintenance + Reports + Prices',
    'role_staff_desc': 'Staff: Create invoices + Add/dispatch stock + Receive devices — no prices or profits',
    'sku_auto_placeholder': 'Leave empty for auto-generation',
    'barcode_auto_placeholder': 'Leave empty for auto-generation',
    'root_category': 'Root Category',
    'new_category_placeholder': 'New category name',
    'export_title': 'Export',
    'export_desc': 'Export all products to Excel file',
    'export_excel': 'Export Excel',
    'import_title': 'Import',
    'import_desc': 'Import products from Excel file (must follow same format)',
    'specialty_general': 'General',
    'specialty_mobiles': 'Mobiles',
    'specialty_laptop': 'Laptop',
    'specialty_computer': 'Computer',
    'specialty_printers': 'Printers',
    'specialty_networks': 'Networks',
    'specialty_cameras': 'Cameras',
    'specialty_other': 'Other',
    'client_name_placeholder': 'Client Name',
    'phone_placeholder': 'Phone',
    'engineer_name_placeholder': 'Engineer Name',
    'phone_optional_placeholder': 'Phone (optional)',
    'name_placeholder': 'Name',
    'order_label': 'Order:',
    'device_label': 'Device:',
    'client_label_view': 'Client:',
    'intake_date_label': 'Intake:',
    'add_record': 'Add Record',
    'date_label': 'Date',
    'action_intake': 'Intake',
    'action_diagnosis': 'Diagnosis',
    'action_repair': 'Repair',
    'action_testing': 'Testing',
    'action_delivery': 'Delivery',
    'action_other': 'Other',
    'write_notes_placeholder': 'Write description or notes...',
    'select_engineer': '-- Select Engineer --',
    'other_engineer': 'Other engineer...',
    'invoice_name_placeholder': 'Name',
    'invoice_phone_placeholder': 'Phone',
    'current_balance': 'Current Balance',
    'record_payment': 'Record Payment',
    'set_balance': 'Set Balance',
    'new_payment_title': 'Record New Payment',
    'movement_type': 'Movement Type',
    'payment_in': 'Payment In (from client)',
    'payment_out': 'Payment Out (to supplier)',
    'add_debt': 'Add New Debt',
    'toast_username_not_found': 'Username not found',
    'toast_wrong_password': 'Wrong password',
    'toast_account_disabled': 'Account disabled',
    'activity_login': 'Login',
    'activity_logout': 'Logout',
    'sync_connected': 'Connected ✅',
    'sync_connected_supabase': 'Connected — Supabase',
    'confirm_replace_data': 'All current data will be replaced. Continue?',
    'currency_egp': 'EGP',
    'scanner_aim_camera': 'Aim camera at barcode',
    'toast_scanned': 'Scanned',
    'confirm_product_not_found_add': 'No product found with barcode: {code}\nWould you like to add a new product?',
    'toast_added_item': 'Added',
    'alert_qty_low': 'Qty',
    'alert_min_stock': 'Min Stock',
    'alert_ready_delivery': 'Ready for delivery',
    'unspecified': 'Unspecified',
    'alert_unpaid_invoices': 'unpaid invoice(s) — Total',
    'no_alerts_msg': 'No alerts ✅',
    'no_login_records': 'No login records',
    'no_movements': 'No movements',
    'warranty_expired_since': 'Warranty {device} — {client} expired {days} days ago',
    'warranty_expires_in': 'Warranty {device} — {client} expires in {days} days',
    'chart_sales_label': 'Sales',
    'chart_purchases_label': 'Purchases',
    'no_devices_chart': 'No devices',
    'maint_under_repair': 'Under Repair',
    'maint_done': 'Done',
    'maint_delivered': 'Delivered',
    'maint_completed': 'Completed',
    'no_data': 'No data',
    'unknown': 'Unknown',
    'this_month': 'This month',
    'no_invoices_recent': 'No invoices',
    'connected_label': 'Connected ✅',
    'not_connected_label': 'Not Connected',
    'sale_invoice_title': 'Sale Invoice',
    'purchase_invoice_title': 'Purchase Invoice',
    'invoice_number': 'Invoice Number',
    'invoice_date': 'Date',
    'client_or_supplier': 'Client',
    'supplier_label': 'Supplier',
    'items_label': 'Items',
    'qty_label': 'Qty',
    'price_label': 'Price',
    'total_label': 'Total',
    'paid_label': 'Paid',
    'remaining_label': 'Remaining',
    'fully_paid': 'Fully Paid',
    'contact_label': 'Contact',
    'by_label': 'By',
    'notes_label': 'Notes',
    'attached_photos': 'Attached Photos',
    'btn_print': 'Print',
    'receipt_label': 'Receipt',
    'share_whatsapp': 'Share WhatsApp',
    'invoice_barcode': 'Invoice Barcode',
    'qr_verify': 'Verification QR',
    'created_by_sms': 'Created by SMS System',
    'click_full_size': 'Click to view full size',
    'thank_you': 'Thank you for your business',
    'btn_view': 'View',
    'btn_edit': 'Edit',
    'btn_add_stock': 'Add Stock',
    'btn_reduce_stock': 'Reduce Stock',
    'existing_label': 'Exists',
    'low_stock_badge': 'Low Stock',
    'available_label': 'Available',
    'view_code': 'Code',
    'view_name': 'Name',
    'view_condition': 'Condition',
    'view_type': 'Type',
    'view_category': 'Category',
    'view_barcode': 'Barcode',
    'view_buy_price': 'Buy Price',
    'view_sell_price': 'Sell Price',
    'view_profit_unit': 'Profit/Unit',
    'view_quantity': 'Quantity',
    'view_min_stock': 'Min Stock',
    'view_description': 'Description',
    'print_barcode': 'Print Barcode',
    'movement_history': 'Movement History',
    'movement_in': 'Stock In',
    'movement_out': 'Stock Out',
    'stock_in_title': 'Stock In',
    'stock_out_title': 'Stock Out',
    'available_qty_only': 'Available quantity is {qty} only',
    'stock_action_in': 'Added',
    'stock_action_out': 'Dispatched',
    'toast_stock_done': '{action} {qty} units done',
    'all_categories_filter': 'All Categories',
    'no_category_option': 'No Category',
    'root_category_option': 'Root Category',
    'no_categories_msg': 'No categories yet',
    'items_count': 'items',
    'subcategory_count': 'subcategories',
    'activity_new_category': 'New category',
    'confirm_delete_category': 'Delete this category?',
    'activity_delete_category': 'Delete category',
    'modal_add_product_title': 'Add New Product',
    'modal_edit_product_title': 'Edit Product',
    'activity_update_product': 'Update product',
    'activity_new_product': 'New product',
    'confirm_delete_product': 'Delete product "{name}"?',
    'activity_delete_product': 'Delete product',
    'excel_sheet_name': 'Inventory',
    'confirm_import_products': 'Products from file will be added. Continue?',
    'activity_import_products': 'Import {count} products',
    'toast_imported_count': 'Imported {count} products',
    'no_main_category': 'No main category',
    'no_results': 'No results',
    'prompt_new_main_category': 'New main category name:',
    'prompt_add_subcategory': 'Add subcategory to "{name}":',
    'prompt_edit_category': 'Edit category name:',
    'confirm_delete_cat_children': 'Category "{name}" has subcategories. Delete all?',
    'cant_delete_has_products': 'Cannot delete "{name}" because it has products',
    'confirm_delete_cat': 'Delete category "{name}"?',
    'add_subcategory': 'Sub',
    'modal_add_client_title': 'Add New Client',
    'modal_edit_client_title': 'Edit Client Details',
    'toast_client_updated': 'Client updated',
    'toast_client_added': 'Client added',
    'confirm_delete_client': 'Delete client "{name}"?',
    'toast_client_deleted': 'Client deleted',
    'view_email': 'Email',
    'view_factory_name': 'Factory Name',
    'view_factory_location': 'Factory Location',
    'view_factory_activity': 'Factory Activity',
    'view_balance': 'Balance',
    'view_notes': 'Notes',
    'invoices_count': 'Invoices',
    'modal_add_supplier_title': 'Add New Supplier',
    'modal_edit_supplier_title': 'Edit Supplier Details',
    'toast_supplier_updated': 'Supplier updated',
    'toast_supplier_added': 'Supplier added',
    'confirm_delete_supplier': 'Delete supplier "{name}"?',
    'toast_supplier_deleted': 'Supplier deleted',
    'items_count_label': 'items',
    'btn_print_view': 'View/Print',
    'btn_record_payment': 'Record Payment',
    'badge_paid': 'Paid',
    'badge_partial': 'Partial',
    'badge_unpaid': 'Unpaid',
    'new_sale_invoice_title': 'New Sale Invoice',
    'new_purchase_invoice_title': 'New Purchase Invoice',
    'select_client': 'Select Client',
    'other_add_client': '+ Other (Add New Client)',
    'select_supplier': 'Select Supplier',
    'other_add_supplier': '+ Other (Add New Supplier)',
    'client_party_label': 'Client',
    'supplier_party_label': 'Supplier',
    'edit_sale_invoice': 'Edit Sale Invoice',
    'edit_purchase_invoice': 'Edit Purchase Invoice',
    'other_short': '+ Other',
    'select_product': 'Select Product',
    'other_add_product': '+ Other (Add New Product)',
    'qty_placeholder': 'Qty',
    'price_placeholder': 'Price',
    'add_new_product_inline': 'Add New Product',
    'product_name_required': 'Product Name *',
    'cost_placeholder': 'Cost',
    'code_optional': 'Code (optional)',
    'save_and_add': 'Save & Add',
    'toast_enter_product': 'Enter product name',
    'toast_add_one_item': 'Add at least one item',
    'toast_select_all_products': 'Select product for all items',
    'toast_sale_saved': 'Sale invoice saved',
    'toast_purchase_saved': 'Purchase invoice saved',
    'invoice_sale_note': 'Sale invoice',
    'invoice_purchase_note': 'Purchase invoice',
    'selected_count_label': 'selected',
    'admin_only_delete_invoices': 'Only admin can delete invoices',
    'confirm_delete_invoices': 'Delete {count} invoices? Stock will be returned. Cannot undo!',
    'toast_deleted_invoices': 'Deleted {count} invoices',
    'confirm_delete_clients': 'Delete {count} clients?',
    'toast_deleted_clients': 'Deleted {count} clients',
    'confirm_delete_suppliers': 'Delete {count} suppliers?',
    'toast_deleted_suppliers': 'Deleted {count} suppliers',
    'confirm_delete_services': 'Delete {count} services?',
    'toast_deleted_services': 'Deleted {count} services',
    'confirm_delete_devices': 'Delete {count} devices?',
    'toast_deleted_devices': 'Deleted {count} devices',
    'confirm_delete_expenses': 'Delete {count} expenses?',
    'toast_deleted_expenses': 'Deleted {count} expenses',
    'confirm_delete_engineers': 'Delete {count} engineers?',
    'toast_deleted_engineers': 'Deleted {count} engineers',
    'admin_only_delete_products': 'Only admin can delete products',
    'confirm_delete_products': 'Delete {count} products? Cannot undo!',
    'toast_deleted_products': 'Deleted {count} products',
    'admin_only_invoices': 'Only admin can delete invoices',
    'confirm_delete_invoice': 'Delete invoice {num}?',
    'toast_invoice_deleted': 'Invoice deleted',
    'remaining_amount': 'Remaining amount',
    'enter_paid_amount': 'Enter paid amount:',
    'toast_payment_recorded': 'Payment recorded',
    'js_under_repair': '🔧 Under Repair',
    'js_done_not_delivered': '✅ Done, Not Delivered',
    'js_delivered_not_paid': '📦 Delivered, Not Paid',
    'js_completed': '💰 Completed & Paid',
    'warranty_badge': 'Warranty',
    'months_label': 'months',
    'overdue_label': 'Overdue!',
    'order_number_label': 'Order #',
    'problem_label': 'Problem',
    'enter_name': 'Enter name',
    'toast_client_supplier_added': '{type} added successfully',
    'manage_clients': 'Manage Clients',
    'manage_suppliers': 'Manage Suppliers',
    'confirm_delete_entity': 'Delete "{name}"?',
    'toast_entity_deleted': 'Deleted {name}',
    'other_add_engineer': '+ Other (Add New Engineer)',
    'toast_enter_engineer_name': 'Enter engineer name',
    'toast_engineer_added': 'Engineer added successfully',
    'modal_new_device_title': 'New Device Intake',
    'other_add_client_short': '+ Other (Add New Client)',
    'modal_edit_device_title': 'Edit Maintenance Order',
    'toast_device_updated': 'Maintenance order updated',
    'toast_device_created': 'Device intake created',
    'maint_expense_note': 'Maintenance - Order',
    'deadline_not_set': 'Not set',
    'toast_device_assigned': 'Device "{device}" assigned to engineer {engineer}',
    'activity_assign_device': 'Assign device "{device}" (order {order}) to engineer {engineer}',
    'task_assigned_title': 'Task Assigned',
    'task_assigned_desc': 'Device assigned to engineer',
    'engineer_assigned': 'Engineer:',
    'device_assigned': 'Device:',
    'problem_assigned': 'Problem:',
    'deadline_assigned': 'Deadline:',
    'instructions_label': 'Instructions:',
    'btn_done': 'Done',
    'activity_task_complete': '{engineer} completed device "{device}" (order {order}){status}',
    'on_time': ' — On time',
    'late': ' — Late',
    'toast_task_complete_ontime': 'Task completed on time — Reward {amount} for engineer {engineer}',
    'toast_task_complete_late': 'Task completed (late) — Engineer {engineer}',
    'toast_task_complete': 'Task completed successfully',
    'activity_warning': 'Warning {count}/{limit} for engineer {engineer} — device "{device}" (order {order})',
    'toast_warning_sent': 'Warning {count}/{limit} sent to engineer {engineer}',
    'confirm_penalty': 'Apply penalty {amount} on engineer {engineer}?',
    'activity_penalty': 'Penalty {amount} on engineer {engineer} — late on device "{device}" (order {order})',
    'toast_penalty_applied': 'Penalty {amount} applied on engineer {engineer}',
    'confirm_delete_maint_order': 'Delete maintenance order {num}?',
    'toast_maint_deleted': 'Maintenance order deleted',
    'available_qty': 'Available',
    'from_stock': 'From Stock',
    'external_purchase': 'External Purchase',
    'select_part': 'Select Part',
    'part_name_placeholder': 'Part Name',
    'supplier_placeholder': 'Supplier',
    'qty_placeholder_parts': 'Qty',
    'price_placeholder_parts': 'Price',
    'device_already_complete': 'Device already completed',
    'confirm_status_change': 'Change status to: {status}?',
    'toast_status_changed': 'Status changed to {status}',
    'view_order_num': 'Order #',
    'view_status': 'Status',
    'view_device': 'Device',
    'view_specs': 'Specs',
    'view_problem': 'Problem',
    'view_intake_date': 'Intake Date',
    'view_client': 'Client',
    'view_client_factory': 'Client Factory',
    'view_engineer': 'Responsible Engineer',
    'view_warranty': 'Warranty',
    'no_warranty': 'No Warranty',
    'task_status_pending': 'Pending',
    'task_status_assigned': 'Assigned',
    'task_status_completed': 'Completed',
    'task_status_overdue': 'Overdue',
    'task_details_title': 'Task Details',
    'task_status_label': 'Task Status',
    'deadline_label': 'Deadline',
    'reward_label': 'Reward',
    'penalty_label': 'Penalty',
    'warnings_label': 'Warnings',
    'task_instructions': 'Task Instructions',
    'btn_complete_task': 'Complete Task',
    'btn_warn': 'Warn',
    'btn_penalize': 'Penalize',
    'device_photos': 'Device Photos',
    'parts_used': 'Parts Used',
    'part_label': 'Part',
    'source_label': 'Source',
    'stock_source': 'Stock',
    'external_source': 'External',
    'stock_parts_cost': 'Stock Parts Cost:',
    'external_parts_cost': 'External Parts Cost:',
    'extra_expenses': 'Extra Expenses:',
    'total_cost': 'Total Cost:',
    'selling_price': 'Selling Price:',
    'profit_label': 'Profit:',
    'qr_maint_order': 'QR Code — Maintenance Order',
    'print_label': 'Print Label',
    'print_receipt': 'Print Receipt',
    'maint_order_details': 'Maintenance Order Details',
    'maint_order_title': 'Maintenance Order',
    'maint_receipt_title': 'Maintenance Receipt',
    'parts_cost_label': 'Parts Cost:',
    'thank_you_receipt': 'Thank you for your business',
    'no_clients_msg': 'No clients',
    'no_suppliers_msg': 'No suppliers',
    'record_payment_btn': 'Record Payment',
    'revenue_details': 'Revenue Details',
    'expenses_details': 'Expenses Details',
    'net_profit_details': 'Net Profit Details',
    'revenue_sales': 'Sales',
    'revenue_maintenance': 'Maintenance',
    'revenue_services': 'Services & Visits',
    'expense_purchases': 'Purchases',
    'expense_general': 'General Expenses',
    'expense_maint_costs': 'Maintenance Costs',
    'profit_sales_revenue': 'Sales Revenue',
    'profit_maint': 'Maintenance Profit',
    'profit_services': 'Services Revenue',
    'profit_purchases_neg': 'Purchases',
    'profit_expenses_neg': 'Expenses',
    'total_sum': 'Total',
    'payment_ledger_client': 'Client Payment Ledger',
    'payment_ledger_supplier': 'Supplier Payment Ledger',
    'select_option': 'Select...',
    'no_movements_recorded': 'No movements recorded',
    'payment_label': 'Payment',
    'debt_label': 'Debt',
    'payment_out_label': 'Payment',
    'adjustment_label': 'Adjustment',
    'invoice_ref': 'Invoice',
    'set_balance_title': 'Set Balance Manually',
    'manual_adjustment': 'Manual adjustment',
    'edit_movement': 'Edit Movement',
    'confirm_delete_movement': 'Delete this movement?',
    'toast_movement_deleted': 'Movement deleted',
    'toast_select_entity': 'Select a client or supplier',
    'toast_enter_valid_amount': 'Enter a valid amount',
    'toast_movement_saved': 'Movement saved',
    'expense_indirect': 'Indirect Expenses',
    'expense_treasury': 'Treasury Expenses',
    'toast_expense_updated': 'Expense updated',
    'toast_expense_added': 'Expense added',
    'confirm_delete_expense': 'Delete this expense?',
    'toast_expense_deleted': 'Expense deleted',
    'modal_new_service_title': 'New Service/Visit',
    'modal_edit_service_title': 'Edit Service/Visit',
    'toast_service_updated': 'Service updated',
    'toast_service_added': 'Service added',
    'confirm_delete_service': 'Delete this service?',
    'toast_service_deleted': 'Service deleted',
    'service_badge_pending': 'Pending',
    'service_badge_in_progress': 'In Progress',
    'service_badge_completed': 'Completed',
    'service_badge_cancelled': 'Cancelled',
    'daily_report_title': 'Daily Report',
    'sale_invoices_title': 'Sale Invoices',
    'purchase_invoices_title': 'Purchase Invoices',
    'no_sales_msg': 'No sales',
    'no_purchases_msg': 'No purchases',
    'expenses_title': 'Expenses',
    'no_expenses_msg': 'No expenses',
    'maintenance_title': 'Maintenance',
    'devices_in': 'Devices In',
    'devices_done': 'Devices Done',
    'monthly_report_title': 'Monthly Report',
    'daily_breakdown': 'Daily Breakdown',
    'th_day': 'Day',
    'th_sales_report': 'Sales',
    'th_purchases_report': 'Purchases',
    'th_expenses_report': 'Expenses',
    'th_profit_report': 'Profit',
    'maint_summary': 'Maintenance Summary',
    'devices_completed': 'Devices Completed',
    'inventory_report_title': 'Inventory Report',
    'by_category': 'By Category',
    'th_item_count': 'Item Count',
    'th_value': 'Value',
    'low_stock_items': 'Low Stock Items',
    'outstanding_report_title': 'Outstanding Amounts',
    'total_outstanding': 'Total Outstanding',
    'user_active': 'Active',
    'user_disabled': 'Disabled',
    'modal_add_user_title': 'Add New User',
    'password_placeholder': 'Password',
    'modal_edit_user_title': 'Edit User',
    'password_keep_placeholder': 'Leave empty to keep unchanged',
    'perm_dashboard': 'Dashboard',
    'perm_inventory': 'Inventory — View',
    'perm_inventory_edit': 'Inventory — Add/Edit/Delete',
    'perm_stock_movement': 'Add/Dispatch Stock',
    'perm_view_prices': 'View Prices & Profits',
    'perm_sales': 'Sales — View',
    'perm_sales_create': 'Sales — Create Invoices',
    'perm_purchases': 'Purchases — View',
    'perm_purchases_create': 'Purchases — Create Invoices',
    'perm_clients': 'Clients',
    'perm_suppliers': 'Suppliers',
    'perm_maintenance': 'Maintenance Workshop',
    'perm_maintenance_intake': 'Device Intake',
    'perm_accounting': 'Accounting',
    'perm_reports': 'Reports',
    'perm_settings': 'Settings',
    'perm_users': 'User Management',
    'toast_user_updated': 'User updated',
    'toast_enter_password': 'Enter password',
    'toast_user_added': 'User added',
    'toast_user_activated': 'User activated',
    'toast_user_deactivated': 'User deactivated',
    'confirm_delete_user': 'Delete this user?',
    'toast_user_deleted': 'User deleted',
    'modal_add_engineer_title': 'Add New Engineer/Tech',
    'modal_edit_engineer_title': 'Edit Engineer/Tech',
    'toast_engineer_updated': 'Engineer/Tech updated',
    'toast_engineer_saved': 'Engineer/Tech added',
    'confirm_delete_engineer': 'Delete this engineer/tech?',
    'confirm_engineer_has_devices': 'This engineer/tech is responsible for {count} devices. Continue?',
    'toast_engineer_deleted': 'Engineer/Tech deleted',
    'timeline_device_intake': 'Device Intake',
    'timeline_device_name': 'Device:',
    'timeline_problem': 'Problem:',
    'timeline_notes': 'Notes:',
    'timeline_diagnosis': 'Diagnosis',
    'timeline_repair': 'Repair',
    'timeline_testing': 'Testing',
    'timeline_completion': 'Completion',
    'timeline_delivery': 'Delivery',
    'timeline_update': 'Update',
    'timeline_maint_complete': 'Maintenance Complete',
    'timeline_device_delivered': 'Device Delivered to Client',
    'timeline_process_complete': 'Process Complete',
    'timeline_new_status': 'New Status:',
    'toast_fill_date_action': 'Please fill in date and action type',
    'toast_record_added': 'Record added',
    'toast_record_updated': 'Record updated',
    'confirm_delete_record': 'Are you sure you want to delete this record?',
    'toast_record_deleted': 'Record deleted',
    'no_activity_log': 'No activity log',
    'notif_low_stock_title': 'Low Stock Alert',
    'notif_unpaid_title': 'Unpaid Invoices',
    'notif_devices_ready_title': 'Devices Ready for Delivery',
    'notif_warranty_title': 'Warranty Alerts:',
    'notif_daily_summary_title': 'Daily Summary',
    'toast_enter_token': 'Enter token first',
    'toast_token_failed': 'Failed — check token',
    'unknown_name': 'Unknown',
    'no_new_messages': 'No new messages. Ask recipient to send /start to bot and try again',
    'people_sent_bot': 'People who messaged the bot:',
    'btn_use': 'Use',
    'toast_found_chats': 'Found {count} chats',
    'toast_connection_err': 'Connection error',
    'toast_chat_id_copied': 'Chat ID copied',
    'toast_enter_token_chatid': 'Enter token and Chat ID',
    'toast_test_success': '✅ Test notification from SMS System — connection working!',
    'toast_sent_success': 'Sent ✅',
    'toast_check_chatid': 'Failed — check Chat ID',
    'toast_check_token_chatid': 'Check token and Chat ID',
    'toast_test_all_sent': 'Test sent to all recipients ✅',
    'toast_recipient_saved': 'Recipient saved ✅',
    'toast_enabled': 'Enabled',
    'toast_disabled': 'Disabled',
    'confirm_delete_recipient': 'Delete this recipient?',
    'toast_deleted_msg': 'Deleted',
    'toast_token_saved': 'Token saved ✅',
    'modal_add_recipient_title': 'Add Recipient',
    'modal_edit_recipient_title': 'Edit Recipient',
    'notif_badge_stock': 'Stock',
    'notif_badge_invoices': 'Invoices',
    'notif_badge_delivery': 'Delivery',
    'notif_badge_warranty': 'Warranty',
    'notif_badge_summary': 'Summary',
    'test_client': 'Test Client',
    'test_supplier': 'Test Supplier',
    'test_invoice_note': 'Test invoice',
    'test_purchase_note': 'Test purchase invoice',
    'toast_test_data_added': 'Added {count} test invoices ✅',
    'return_from_invoice': 'Return from invoice',
    'toast_return_created': 'Return created',
    'no_barcode': 'No barcode',
    'edit_list_btn': 'Edit List',
    'type_here': 'Type here...',
    'save_label': 'Save',
    'search_placeholder': 'Search...',
    'choose': 'Choose',
    'other_option': 'Other...',
    'edit_list_title': 'Edit List',
    'add_new_item': 'Add new item...',
    'btn_add': 'Add',
    'save_changes': '💾 Save Changes',
    'list_empty': 'List is empty',
    'confirm_delete_item': 'Delete "{item}"?',
    'choose_default': 'Choose...',
    'other_add': '➕ Other...',
    'expense_cat_rent': 'Rent',
    'expense_cat_salaries': 'Salaries',
    'expense_cat_utilities': 'Electricity & Water',
    'expense_cat_transport': 'Transport',
    'expense_cat_maintenance': 'Maintenance',
    'type_accessory': 'Accessory',
    'type_cable': 'Cable',
    'type_charger': 'Charger',
    'pay_paid': 'Paid',
    'pay_unpaid': 'Unpaid',
    'pay_partial': 'Partial',
    'ds_under_repair': 'Under Repair',
    'ds_repaired': 'Repaired',
    'ds_delivered': 'Delivered',
    'ds_completed': 'Completed',
    'ss_scheduled': 'Scheduled',
    'ss_ongoing': 'Ongoing',
    'ss_done': 'Done',
    'ss_cancelled': 'Cancelled',
    'admin_name': 'Admin',
    'no_barcode_msg': 'No barcode',
    'return_note': 'Return from invoice {num}',
}

# Build the new translations block to insert
ar_lines = []
en_lines = []
for key in new_translations_ar:
    ar_val = new_translations_ar[key].replace("'", "\\'")
    en_val = new_translations_en[key].replace("'", "\\'")
    ar_lines.append(f"    {key}: '{ar_val}',")
    en_lines.append(f"    {key}: '{en_val}',")

ar_block = '\n'.join(ar_lines)
en_block = '\n'.join(en_lines)

# Insert new translations before closing of ar and en sections
# Find the end of ar section (repair_profit line) and add new keys
content = content.replace(
    "    repair_profit: 'الربح:',\n  },\n  en: {",
    f"    repair_profit: 'الربح:',\n\n    // Auto-generated translations v7.2\n{ar_block}\n  }},\n  en: {{"
)

# Hmm, that's tricky because of the object structure. Let me try differently.
# Actually let me just find the exact insertion points.

print("Script loaded, checking structure...")

# Find ar closing and en closing
ar_end_marker = "    repair_profit: 'الربح:',"
en_end_marker = "    repair_profit: 'Profit:',"

if ar_end_marker in content:
    print("Found ar end marker")
if en_end_marker in content:
    print("Found en end marker")
